const router     = require("express").Router();
const auth       = require("../middleware/auth");
const rbac       = require("../middleware/rbac");
const controller = require("../controllers/issueController");
router.use(auth);
router.get("/", controller.getAllIssues);
router.get("/my-tasks", controller.getMyTasks);
router.get("/my-issues", controller.getMyIssues);
router.get("/project/:projectId", controller.getIssuesByProject);
router.post("/", rbac("developer", "tester", "admin", "superadmin"), controller.createIssue);
router.put("/:id/status", rbac("developer", "tester", "admin", "superadmin"), controller.updateIssueStatus);
router.put("/:id", rbac("developer", "tester", "admin", "superadmin"), controller.updateIssue);
router.delete("/:id", rbac("admin", "superadmin"), controller.deleteIssue);
module.exports = router;
